from .settings import (
    BASE_DIR,
    RESULTS_DIR,
    WIN_SECONDS,
    TRANSITION_PATTERNS,
    BASELINE_WINDOW,
    STRICT_POST_WINDOW,
    DETAILED_WINDOWS,
    CLUSTER_ANALYSIS_WINDOW,
    N_PERMUTATIONS,
    ALPHA_CLUSTER,
)